apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        environment: prod
    spec:
      containers:
      - name: my-app
        image: kasyapdocker123/anime-app:latest
        ports:
        - containerPort: 3000
