apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch-deployment
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:latest
          ports:
            - containerPort: 7700

