basePath: /api
definitions:
  anime.PaginatedAnimeResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/database.Anime'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
      totalPages:
        type: integer
    type: object
  database.Anime:
    properties:
      aired:
        type: string
      animeType:
        type: string
      description:
        type: string
      episode:
        type: integer
      genre:
        type: string
      id:
        type: integer
      imageUrl:
        type: string
      rank:
        type: integer
      rating:
        type: string
      score:
        type: number
      studio:
        type: string
      title:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is an anime API server.
  title: Anime API
  version: "2.0"
paths:
  /anime:
    get:
      description: Get a list of all anime with optional pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/anime.PaginatedAnimeResponse'
      summary: Get all anime
  /anime/{id}:
    get:
      description: Get a single anime by its ID
      parameters:
      - description: Anime ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Anime'
      summary: Get anime by ID
  /anime/search:
    get:
      description: Search for anime by name
      parameters:
      - description: Anime name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Anime'
            type: array
      summary: Search anime
swagger: "2.0"
